version: '3.7'

services:

  # Database
  nuxtpress.mysql:
    container_name: ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
    image: mysql:5.7
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${NUXTPRESS_MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${NUXTPRESS_DB_NAME:-nuxtpressz_database}
      MYSQL_USER: ${NUXTPRESS_MYSQL_USER:-nuxtpresszadmin}
      MYSQL_PASSWORD: ${NUXTPRESS_MYSQL_PASSWORD:-zpassword}
    ## if switch to just using .env file
    # env_file:
    #   - ./env/db.env
    networks:
      - wpsite

  # phpmyadmin
  nuxtpress.phpmyadmin:
    container_name: ${NUXTPRESS_PHPMYADMIN_CONTAINER:-nuxtpress.phpmyadmin}
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
      MYSQL_ROOT_PASSWORD: ${NUXTPRESS_MYSQL_ROOT_PASSWORD:-password}
    networks:
      - wpsite

  nuxtpress.fwp:
    container_name: ${NUXTPRESS_WP_CONTAINER:-nuxtpress.fwp}
    build:
      context: ./backend/docker
    restart: always
    depends_on:
      - ${NUXTPRESS_MYSQL_CONTAINER:-nuxtpress.mysql}
    ports:
      - '${NUXTPRESS_WP_PORT:-3080}:80'
    environment:
      NUXTPRESS_WP_PORT: ${NUXTPRESS_WP_PORT:-3080}
      WORDPRESS_DB_HOST: ${NUXTPRESS_DB_HOST:-nuxtpress.mysql:3306}
      WORDPRESS_DB_USER: ${NUXTPRESS_DB_USER:-nuxtpresszadmin}
      WORDPRESS_DB_PASSWORD: ${NUXTPRESS_DB_PASSWORD:-zpassword}
      WORDPRESS_DB_NAME: ${NUXTPRESS_DB_NAME:-nuxtpressz_database}
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  wordpress:
